Add missing xml files to the test war file to fix the following error:
com.sun.ws.management.client.exceptions.FaultException: SOAP Fault: The service cannot comply with the request due to internal processing errors.
     Actor:
      Code: env:Receiver
  Subcodes: wsman:InternalError
    Detail: Failed to load Get.xml from war